apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
data:
  hive-site.xml: |
    <configuration>
      <property>
        <name>hive.server2.transport.mode</name>
        <value>http</value>
      </property>
      <property>
        <name>fs.default.name</name>
        <value>hdfs://{{ .Values.connect.hdfs.namenode }}</value>
      </property>
      <property>
        <name>hive.server2.thrift.max.worker.threads</name>
        <value>500</value>
      </property>
      <property>
        <name>hive.metastore.event.db.notification.api.auth</name>
        <value>false</value>
      </property>
      <property>
          <name>hive.metastore.uris</name>
          <value />
      </property>  
      <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:mysql://{{ .Values.connect.mysql.server }}/hive?createDatabaseIfNotExist=true&amp;useSSL=false</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>com.mysql.jdbc.Driver</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>{{ .Values.connect.mysql.username }}</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>{{ .Values.connect.mysql.password }}</value>
      </property>
      <property>
          <name>hive.metastore.schema.verification</name>
          <value>false</value>
      </property>
    </configuration>

  bootstrap.sh: |
    export PATH=/opt/hive/bin:$PATH
    HADOOP_HOME=/usr/local/hadoop
    echo "Schema Init:"
    schematool -dbType mysql -initSchema
    hive --service hiveserver2 --hiveconf hive.root.logger=INFO,console
