apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hive.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "hive.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: hiveserver
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
           - "/bin/bash"
           - "/tmp/bootstrap.sh"
          ports:
            - name: http
              containerPort: 10001
              protocol: TCP
            - name: ui
              containerPort: 10002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: ui
              initialDelaySeconds: 120
              timeoutSeconds: 5
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
              readOnly: true
            - name: bootstrap
              mountPath: /tmp/bootstrap.sh
              subPath: bootstrap.sh
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "hive.fullname" . }}
        - name: bootstrap
          configMap:
            name: {{ include "hive.fullname" . }}