apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-http
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHTTP }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hive.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-ui
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.portUI }}
      targetPort: ui
      protocol: TCP
      nodePort: {{ .Values.service.nodePortUI }}
      name: ui
  selector:
    app: {{ include "hive.name" . }}
    release: {{ .Release.Name }}